### ISSUE TITLE
Some tests in mks::eigen are failing

### ISSUE THREAD

**Issue by cernoch** [master-keying/mks#24] opened 2018-04-05 14:57 UTC
In the 36fe56d2fb3b1c17fde33311b9d3e29ec29819f4 commit, tests for `mks::eigen` stopped working.

My output of `./tests`:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests is a Catch v2.1.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
eigen::diagonal
-------------------------------------------------------------------------------
/mnt/x/mks/src/test/cpp/eigen_test.cpp:13
...............................................................................

/mnt/x/mks/src/test/cpp/eigen_test.cpp:167: FAILED:
  REQUIRE( eig.solution_size() == 5 )
with expansion:
  0 == 5
...
```

Apparently, the validator succeeds, but the solution is empty.

**Comment by cernoch** [comment] 2018-04-05 15:02
I suggest to create a PR from `eigen_refactoring` after this bug is fixed.

**Comment by kryskmar** [comment] 2018-04-10 09:25
Bug is now fixed. It was caused by wrong saving values to solution_size variable.

**Closed by kryskmar** 2018-04-10 09:25 UTC
Labels: bug
